//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsMEPyD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleados { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string CodigoEmpleado { get; set; }
        public string CorreoEmpleados { get; set; }
        public string TelefonoOficina { get; set; }
        public string Celular { get; set; }
        public string Cargo { get; set; }
        public string Departamento { get; set; }
        public Nullable<int> IdCompañia { get; set; }
    
        public virtual Compañia Compañia { get; set; }
    }
}
